### ISSUE TITLE
Code Issue

### ISSUE THREAD

**Issue by kobusdbr** [finity69x2/fan-percent-button-row#11]
Good day. Please could someone assist. I am not a coder so not sure what I am doing wrong. I copied this code from where I installed the card.

Here is my code:
type: entities
title: Luke Fan
show_header_toggle: false
entities:
  - entity: fan.sonoff_luke_fan
    name: Luke Fan
    type: 'custom:fan-percent-button-row'
    reverseButtons: true
    customTheme: true
    isOnLowColor: 'rgb(255, 0, 0)'
    isOnMedColor: '#888888'
    isOnHiColor: '#222222'
    buttonInactiveColor: '#aaaaaa'
    isOffColor: purple

Error message in Home assistance:

Visual editor is not supported for this configuration:
The provided value for "entities.0" is not supported by the visual editor. We support (Object<{entity,name,icon,image,secondary_info,format,state_color,tap_action,hold_action,double_tap_action}> | string | Object<{type,name,action_name,tap_action,hold_action,double_tap_action}> | Object<{type,view,dashboard,name,icon,hide_if_unavailable}> | Object<{type,row,conditions}> | Object<{type,style}> | Object<{type,label}> | Object<{type,url,name,icon}> | Object<{type,entities}> | Object<{type,entity,attribute,prefix,suffix,name}> | Object<{type,name,service,icon,action_name,service_data}>) but received ({"entity":"fan.sonoff_luke_fan","name":"Luke Fan","type":"custom:fan-percent-button-row","reverseButtons":true,"customTheme":true,"isOnLowColor":"rgb(255, 0, 0)","isOnMedColor":"#888888","isOnHiColor":"#222222","buttonInactiveColor":"#aaaaaa","isOffColor":"purple"}).You can still edit your config in YAML.

**Comment by finity69x2** [comment]
You need to use the yaml editor to code the card.

the UI config isn't supported.
