### ISSUE TITLE
Option to hide name

### ISSUE THREAD

**Issue by mohyat** [finity69x2/fan-percent-button-row#13]
Can you add option to hide name and icon ? I need only buttons.

I added like this, but there is emty place is before buttons:
```
name: ' '
icon: ' '
```

**Comment by magnetic157** [comment]
Hello, can we have a 4th button option?

Lutron Caseta offers 25%, 50%, 75% and 100% fan speeds - the current setup only seems to allow 3 speeds on the percentage section.

**Comment by finity69x2** [comment]
I have no control over that portion of the entity row.

You will need to address that request to the HA frontend developers repo
