### ISSUE TITLE
This could be used a quick set for Climate

### ISSUE THREAD

**Issue by wreuvers** [finity69x2/fan-percent-button-row#16]
I love this for Fans, thank you so much. And it would be great if you could please evolve it to suppurt more than just fans. For example, it would be a huge win if we could use it to quicky preset cooling values on airconditioners (Climate)
For example, 
Kitchen Cooling    69F  |   72F   |   75F   |    Off

**Comment by finity69x2** [comment]
I don't have any climate devices so it would be difficult for me to develop one but I will look into it.

Thanks for another use suggestion.

**Comment by wreuvers** [comment]
This would be a great solution to almost any device types - for water flow, it would be 3 gpm | 4 gpm | 5 gpm.
Battery charging of solar battery storage 3kW | 4kW | 5kW

Call it preset-button-row and allow the values to be sent to the sensor. Could be any sensor!

**Comment by finity69x2** [comment]
the issue with that is that the buttons need to call a specific service.

the plugin is designed with the service call built in. And I can't see a way (reasonably easily) that I could make the buttons completely "service call agnostic" or selectable.
