### ISSUE TITLE
Unable to send repeat command

### ISSUE THREAD

**Issue by goobags** [finity69x2/fan-percent-button-row#18]
Hi,

I have just set this up for my 4 fans through a Bond bridge. When the fan state is changed, particularly from off to on when using the OEM remote, the state is not changed in HA (which I completely understand and that's fine). However when I try to turn the fan off from Lovelace and the off button is already highlighted as the assumed state, the off command is never send, it requires pressing any other speed button then pressing off. Is this a known glitch or is it just me? 

I can always send the off command through the Bond integration even when the fan is assumed to be in the off state. Also I noticed the off command is send twice through Lovelace is that normal? She who must be obeyed is wondering why there is a second beep.

**Comment by finity69x2** [comment]
I just published a new release that allows you to not disable the buttons.

see the readme for the option to use.

**Comment by goobags** [comment]
Thanks mate I’ll give it a go tonight

**Comment by goobags** [comment]
Success, thank you again
