### ISSUE TITLE
Repository not in HACS

### ISSUE THREAD

**Issue by jazzyisj** [finity69x2/fan-percent-button-row#2]
Just a heads up, this repository isn't showing up in HACS.  I had to add it as a custom repository.

Newest edit: Randomly a day later after several restarts (was working on something else) this plugin started working...  ugh.

~~Edit:  The component is also not working (for me anyway).  Have hard cleared cache, restarted, triple checked config.~~

**Comment by finity69x2** [comment]
Yeah, I'm not sure why Ludeus isn't adding some of the repos to hacs.

There's 5 that are waiting for merging even tho all checks have passed.

Thanks for the heads up and I'm glad you got it working.
