### ISSUE TITLE
Ability to hide "off" and/or other buttons.

### ISSUE THREAD

**Issue by wimb0** [finity69x2/fan-percent-button-row#22]
Is it possible to add an option to hide the "off" button or other buttons?
Some fans do not have an "off" option, or should not be switched off.
For example, the mechanical ventilation in my house should always run and cannot be switched off unless you unplug the cable.

**Comment by finity69x2** [comment]
No you can't hide any buttons except the middle speed button (isTwoSpeedFan option).

**Comment by richardbabangida** [comment]
I like to have this as well!
