### ISSUE TITLE
customSetpoints: true

### ISSUE THREAD

**Issue by 19leva89** [finity69x2/fan-percent-button-row#23]
When setting customSetpoints: true and
lowPercent: 30
medPercent: 60
hiPercent: 100
percentage value still remains 33% 66% 100%

**Comment by Oleg-Sob** [comment]
You need to write not Percent , but Percentage.

**Comment by finity69x2** [comment]
did the suggestion by Oleg-Sob fix your issue?

**Comment by 19leva89** [comment]
Yes, thanks, everything works! 
In the old version of the program there was a config:
lowPercent: 30
medPercent: 60
hiPercent: 100

In the new version of the program, the config has become:
lowPercentage: 30
medPercentage: 60
hiPercentage: 100

**Comment by finity69x2** [comment]
Nope, I just looked back at the initial release and those settings have always been "xxxPercentage" and not "xxxPercent".

But I'm glad it' working for you.

**Comment by 19leva89** [comment]
![log](https://user-images.githubusercontent.com/71250243/154514670-68a52669-4245-4803-8c78-52b074ea00e7.png)
