### ISSUE TITLE
Add support for hiding the Off Button

### ISSUE THREAD

**Issue by denniswham** [finity69x2/fan-percent-button-row#24]
Similar to [fan-control-entity-row](https://github.com/finity69x2/fan-control-entity-row)

**Comment by finity69x2** [comment]
I saw that one coming... :D

Done.

Should be in HACS soon.

**Comment by denniswham** [comment]
Installed update with HACS. Works like a charm, many thanks!

**Comment by denniswham** [comment]
Within a browser on PC, the off button is hidden. In the iOS app, it is still visible - looking at the very same dashboard.

**Comment by denniswham** [comment]
Never mind, it works now

**Comment by Waylikemark** [comment]
![D9254FD4-A63F-43C7-8FD2-EF3332C54164](https://user-images.githubusercontent.com/75362952/161643829-035a9728-ece9-4729-bb03-88cdf957a156.jpeg)
![6A8A2455-07A4-42A1-B731-3E5060798B4E](https://user-images.githubusercontent.com/75362952/161643838-7bea0c8b-cdfb-48fc-a070-8d7639c6f155.jpeg)
![0A17065D-471B-4249-B0F5-51525D58302C](https://user-images.githubusercontent.com/75362952/161643452-8b274439-3cd7-4b76-8925-9eadc1874986.jpeg)
Doesn’t work on my end. It works on fan-control-entity-row with exact the same config and the exact same entity though. Also is the theming different.

HA 2022.04
