### ISSUE TITLE
Requesting an additional button for Leviton ZW4SF.

### ISSUE THREAD

**Issue by robebade** [finity69x2/fan-percent-button-row#26]
If it's possible, a fifth button for "max" would be great! Leviton ZW4SF has it's percentage as 25-low, 50-medium, 75-high, and 100-max.

**Comment by ausrobbo** [comment]
I would also like this for Lutron Casetta fan controllers off, 25, 50, 75, 100.
Looked through the code, seems like number of buttons could be a config option to resize the button divs?

**Comment by finity69x2** [comment]
"seems like number of buttons could be a config option to resize the button divs?'

maybe but there would still be the requirement to code the button functionality themselves.

I've more than once been asked to add buttons and i always decline. I've been asked to provide up to 10 buttons before.

i think that there needs to be a balance of functionality and screen space/aesthetics. four buttons are where i think the sweet spot is.

sorry i won't be adding any more buttons.
