### ISSUE TITLE
Hiding off button not working

### ISSUE THREAD

**Issue by Waylikemark** [finity69x2/fan-percent-button-row#28]
![D9254FD4-A63F-43C7-8FD2-EF3332C54164](https://user-images.githubusercontent.com/75362952/161643829-035a9728-ece9-4729-bb03-88cdf957a156.jpeg)
![6A8A2455-07A4-42A1-B731-3E5060798B4E](https://user-images.githubusercontent.com/75362952/161643838-7bea0c8b-cdfb-48fc-a070-8d7639c6f155.jpeg)
![0A17065D-471B-4249-B0F5-51525D58302C](https://user-images.githubusercontent.com/75362952/161643452-8b274439-3cd7-4b76-8925-9eadc1874986.jpeg)
Doesn’t work on my end. It works on fan-control-entity-row with exact the same config and the exact same entity though. Also is the theming different.

HA 2022.04

_Originally posted by @Waylikemark in https://github.com/finity69x2/fan-percent-button-row/issues/24#issuecomment-1088075820_

**Comment by finity69x2** [comment]
It's working fine in my system.

Have you updated to the latest release?

**Comment by Waylikemark** [comment]
According to HACS i have the latest version (1.8)

**Comment by finity69x2** [comment]
I'm not sure what to tell you except to try to clear your browser cache and do a hard reload.

F12 then right click on the "reload this page" button at the top right then select "empty cache and hard reload".

**Comment by Waylikemark** [comment]
It now works since HA 2022.5.X, once i downgrade to 2022.4.X the issue is back. So i dont think its cache related, but it works and thats most important.

**Comment by finity69x2** [comment]
Glad it's working.

But I'm not sure why the HA version would have been the issue either since mine has worked correctly the whole time.
