### ISSUE TITLE
Background "box"

### ISSUE THREAD

**Issue by Sineos** [finity69x2/fan-percent-button-row#31]
Please excuse my probably absolute beginner question:
![grafik](https://user-images.githubusercontent.com/4459312/185811003-b11c54c2-e6a6-4742-851b-9ea47c40d43a.png)

How do I get the control into such a bounding box like the other elements?

**Comment by finity69x2** [comment]
Could you post the config for the card (not just my plugin portion).

**Comment by Sineos** [comment]
I think I solved my issues (still a HA n00b):
* The definition needs to go into an Entities card
* It is not meant standalone. The presence of the dedicated card lead me on the wrong track

Is this understanding correct?

**Comment by finity69x2** [comment]
yes, that's correct.

the example code in the readme even shows it being used in an entities card
