### ISSUE TITLE
Light button?

### ISSUE THREAD

**Issue by NonaSuomy** [finity69x2/fan-percent-button-row#33]
Hi is there a way to add a light button to the end of the fan row? 

Just a single button with a lightbulb icon on it for the light that when you tap either turns the light on or off depending on the light's current state?

**Comment by finity69x2** [comment]
Not using this plugin.

I'm not sure of any that can do that.

maybe a custom plugin called multiple entity row?

https://github.com/benct/lovelace-multiple-entity-row
