### ISSUE TITLE
Support more than three speeds

### ISSUE THREAD

**Issue by 0xJoeMartin** [finity69x2/fan-percent-button-row#35]
I have a 6-speed fan.  Could you add support for more than three speeds?

Obviously, I could use the existing customization to create buttons for 3 of the speeds.  But would like the ability to create all 6 speed buttons.

**Comment by finity69x2** [comment]
I've had this request a lot and I still really don't want to do it.

I've had people ask for buttons for 10 speeds before. 

So I have made the compromise between screen real estate and functionality. and 4 buttons is that compromise.

Sorry.
