### ISSUE TITLE
Polyer Deprecation

### ISSUE THREAD

**Issue by breakthestatic** [finity69x2/fan-percent-button-row#38]
I started receiving warnings in my Home Assistant logs about Polymer being deprecated in favor of lit (see https://developers.home-assistant.io/blog/2023/04/04/deprecating_polymer/) after upgrading to 2023.4. It looks like starting in the next release (2023.5) Polymer will be completely removed, breaking this library.

**Comment by fishbone-git** [comment]
and as expected, with the 2023.5b0 the percent button row is broken

**Comment by finity69x2** [comment]
I'm working on it.

the polymer deprecation caught me off guard with such little notice and I have to figure out how to update it.

**Comment by finity69x2** [comment]
Another user has created a PR for the update.

I've merged it so it should be available in HACS soon
