### ISSUE TITLE
Uncaught ReferenceError: Polymer is not defined

### ISSUE THREAD

**Issue by nak714** [finity69x2/fan-percent-button-row#42]
I have used this customization for the last 2 years (awesome custom button) and after upgrading HA, HACS and the latest version of fan-percent button row it is not longer working.  
I am seeing the following error in the logs:
2023-05-12 13:59:14.804 ERROR (MainThread) [frontend.js.latest.202305033] http://X.X.X.X/hacsfiles/fan-percent-button-row/fan-percent-button-row.js:9:35 Uncaught ReferenceError: Polymer is not defined

I see the following on my front end:

![image](https://github.com/finity69x2/fan-percent-button-row/assets/58399190/84402bad-6edb-4170-87c6-1ec2918ab246)

I am running HA 2023.5.2, HACS 1.32.1 and the latest version of fan-percent.

**Comment by finity69x2** [comment]
> latest version of fan-percent.

Are you sure?

that should have been fixed in version 3.0 released a few days ago.

**Comment by wvdeadhead** [comment]
I'm seeing the same thing even after clearing browser cache/cookies and updating to 3.1:

Logger: frontend.js.latest.202305031
Source: components/system_log/__init__.py:257
First occurred: 8:05:04 AM (2 occurrences)
Last logged: 8:05:22 AM

https://my.domain/hacsfiles/fan-percent-button-row/fan-percent-button-row.js:9:35 Uncaught ReferenceError: Polymer is not defined

my ui-lovelace.yaml:

```
- entity: fan.living_room_fan
  type: custom:fan-percent-button-row
  name: " "
  customTheme: false
  state_color: true
```

my configuration.yaml:

```
- url: /hacsfiles/fan-percent-button-row/fan-percent-button-row.js
  type: module
```

**Comment by nak714** [comment]
I am running 3.1. 

As a FYI I am having the same issue with Cover Position Preset Row button.

![image](https://github.com/finity69x2/fan-percent-button-row/assets/58399190/09d006b3-1363-4788-b175-05efb0878124)

**Comment by wvdeadhead** [comment]
Interestingly, Companion App version "beta-10008-d81913b7-full" does not throw an error and the buttons work.

**Comment by finity69x2** [comment]
This seems to definitely be a browser cache issue especially if it works on a different browser.

I'm not getting any polymer errors in my HA using the latest version. And I'm not getting any other notifications from other users so I have to assume that the polymer issue is fixed.

If you already cleared the cache and it's still not working then I don't have much more to offer for getting it to work.

The only thing I can suggest is to uninstall the plugin completely (including from the resources), restart HA, do a hard reload of the browser page (on Chrome hit F12 then right click the reload button and select "Empty Cache and Hard Reload"), then re-install the plugin, restart HA and do the hard reload again to see if that makes it work.

**Comment by wvdeadhead** [comment]
At least in my case, you are correct, it was a browser cache issue.  Another round of cache clearing and a browser restart fixed the problem.
