### ISSUE TITLE
Feature request - icon color

### ISSUE THREAD

**Issue by jpettitt** [finity69x2/fan-percent-button-row#43]
Any chance of adding icon color control for each preset level?

**Comment by Amishman** [comment]
Is this what you are looking for or is it something else?

<html><body>


isOffColor | String | No | '#f44c09' | Sets the color of the 'Off' button if fan is off
-- | -- | -- | -- | --
isOnLowColor | String | No | '#43A047' | Sets the color of the 'Low' button if fan is on low percent speed
isOnMedColor | String | No | '#43A047' | Sets the color of the 'Med' button if fan is on medium percent speed
isOnHiColor | String | No | '#43A047' | Sets the color of the 'Hi' button if fan is on high percent speed
buttonInactiveColor | String | No | '#759aaa' | Sets the color of the the buttons if that selection is not "active"


</body>
</html>

**Comment by jpettitt** [comment]
Not quite, I was looking for the icon on the left to reflect the color of the selected speed - so in the example below it would be blue

![image](https://github.com/finity69x2/fan-percent-button-row/assets/524856/d5213d6d-6f6a-481a-ab7a-6f57dc0dc871)

**Comment by randellmatt** [comment]
I would like to request this feature also. It currently always looks like off is selected when the fan is on. It would be great to see its state at-a-glance.

**Comment by randellmatt** [comment]
Apologies. I have worked it out. I thought the icon would rely on the percentage value, but I had to set the fan state also.
