### ISSUE TITLE
Adding another speed?

### ISSUE THREAD

**Issue by nickastaldo** [finity69x2/fan-percent-button-row#46]
Hello! Is there any way to add an additional block on this awesome card? I have a 4-speed fan, so it would be awesome to have your card display/send command for, off, 25%, 50%, 75%, and 100%. I couldn't see how to do it inside the config, but I'm definitely not a pro. Thanks!

**Comment by rubicon** [comment]
I would love this.

**Comment by finity69x2** [comment]
It's been asked a hundred times.

But as before I really don't want to take up that much space on the row for buttons.

So I unfortunately have to decline the request.

**Comment by alekseyn1** [comment]
If anyone finds this issue. I have modified the file for 4 speeds here https://github.com/alekseyn1/fan-percent-button-row-4/blob/main/dist/fan-percent-button-row.js
